# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_0_1/design_1_proc_sys_reset_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_1 || ORIG_REF_NAME==design_1_proc_sys_reset_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_1_1/design_1_proc_sys_reset_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_1_1 || ORIG_REF_NAME==design_1_proc_sys_reset_1_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_1/design_1_clk_wiz_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_1 || ORIG_REF_NAME==design_1_clk_wiz_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI4Stream_UART_0_1/design_1_AXI4Stream_UART_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_AXI4Stream_UART_0_1 || ORIG_REF_NAME==design_1_AXI4Stream_UART_0_1} -quiet] -quiet

# XDC: c:/Users/valer/Documents/desd-labs/LAB3/LoopBack2M/LoopBack2M.gen/sources_1/bd/design_1/design_1_ooc.xdc
