# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/valer/Documents/desd-labs/LAB3/DAW/DAW.srcs/sources_1/bd/design_1/ip/design_1_AXI4Stream_UART_0_2/design_1_AXI4Stream_UART_0_2.xci
# IP: The module: 'design_1_AXI4Stream_UART_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/valer/Documents/desd-labs/LAB3/DAW/DAW.gen/sources_1/bd/design_1/ip/design_1_AXI4Stream_UART_0_2/design_1_AXI4Stream_UART_0_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_AXI4Stream_UART_0_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/valer/Documents/desd-labs/LAB3/DAW/DAW.srcs/sources_1/bd/design_1/ip/design_1_AXI4Stream_UART_0_2/design_1_AXI4Stream_UART_0_2.xci
# IP: The module: 'design_1_AXI4Stream_UART_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/valer/Documents/desd-labs/LAB3/DAW/DAW.gen/sources_1/bd/design_1/ip/design_1_AXI4Stream_UART_0_2/design_1_AXI4Stream_UART_0_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_AXI4Stream_UART_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
