set_property SRC_FILE_INFO {cfile:C:/Users/valer/Documents/desd-labs/LAB3/DAW/DAW.srcs/constrs_1/new/pins.xdc rfile:../../../DAW.srcs/constrs_1/new/pins.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W19 [get_ports btnL]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T17 [get_ports btnR]
